✨ Feat: 단체 등록 css 기능 추가 중
CodeCloud-at-DGU/CodeCloud pull request #6
Opened 2023-12-02 18:59 UTC by dudtlstm

아직 할 거 많아요 ^^

2023-12-03 09:02 UTC, seochan99 requested changes
전반적으로 불필요한 코드가 많음.. 
아무래도, index.jsp를 고대로 복붙해서 거기에 필요내용을 추가한듯한데, 필요없는 내용은 삭제하길 바람

2023-12-03 09:02 UTC, seochan99 commented on src/main/webapp/resources/css/group/groupRegisterResult.css
> +	margin: 100px;
px사용금지 rem으로하셈

2023-12-03 09:02 UTC, seochan99 commented on src/main/webapp/resources/css/group/groupRegisterResult.css
> +	font-size: small;
small같은거 금지 rem으로 쓰셈

2023-12-03 09:02 UTC, seochan99 commented on src/main/webapp/resources/css/group/groupRegisterResult.css
> +	font-size:large;
large같은거 금지 rem으로 쓰셈

2023-12-03 09:02 UTC, seochan99 commented on src/main/webapp/views/group/groupRegister.jsp
> +    <%@ include file="../main/main.jsp" %>
main은 여기서 왜들고오지

2023-12-03 09:02 UTC, seochan99 commented on src/main/webapp/views/group/groupRegisterResult.jsp
> +        <link rel="stylesheet" type="text/css" href="../../resources/css/main/main.css">
이건 왜들고오는거지

2023-12-03 15:06 UTC, dudtlstm commented on src/main/webapp/views/group/groupRegister.jsp
> +    <%@ include file="../main/main.jsp" %>
안 뺐ㄴㅔ 지송

2023-12-04 16:40 UTC, leejs0823 approved these changes
굿!

2023-12-04 16:42 UTC, merged