✨ Feat: 메인 페이지 화면단 구성
CodeCloud-at-DGU/CodeCloud pull request #7
Opened 2023-12-03 19:05 UTC by leejs0823

보이는 부분만 구성했습니다
필요없는 코드 써있는 거 있나 확인 좀 해주십쇼...
그리고 px 전부 rem 으로 바꿔서 써야하는건가요??

2023-12-03 19:08 UTC, seochan99 requested changes
고생했어요 px -> rem으로 변경해주세요.
10px = 1rem으로 생각하시면됩니다.

2023-12-03 19:08 UTC, seochan99 commented on src/main/webapp/resources/css/main/main.css
> +	padding:20px;
얘만 앞에 스페이스없어요

2023-12-04 11:24 UTC, seochan99 approved these changes
고생많았어요~

2023-12-04 11:24 UTC, seochan99 commented on src/main/webapp/resources/css/main/main.css
>      font-weight: bold;
weigt같은거 bold체를 별도로 저희가 지정안한걸로 아는데..했나요?
이게 몇인가요?

2023-12-04 16:44 UTC, dudtlstm approved these changes
정선아 넌 진짜 멋지다....!!! 수고해써용
매일 새벽 한 시에 봐(하트)

2023-12-04 16:45 UTC, merged